allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
allow-panic-in-tests = true
absolute-paths-max-segments = 4

[[disallowed-types]]
path = "axum::extract::Query"
reason = "Use serde_qs::axum::QsQuery instead"

[[disallowed-types]]
path = "axum::Form"
reason = "Use serde_qs::axum::QsForm instead"
